apiVersion: 1

contactPoints:
  - name: Discord Notifications
    receivers:
      - type: slack
        uid: discord_webhook
        settings:
          url: https://discord.com/api/webhooks/1501904313281155105/orW-2LWEDLpIsVCj1X99XsFpeMM4IgHE-QEZ4mBNnVkzHcaYju-08iHDF2SyGBcJg6oR/slack
          username: "PotBuddy Monitor"
          title: |-
            {{ range .Alerts.Firing }}{{ .Annotations.summary }}{{ end }}
          text: ""
