local_mqtt:
  broker: "tcp://mqtt.kaminjitt.com:1883"
  client_id: "potbuddy-local-node"
  sub_topic: "potbuddy/+/raw"
  pub_topic: "potbuddy/processed"

cloud_mqtt:
  broker: "tcp://mqtt.kaminjitt.com:1883"
  client_id: "potbuddy-cloud-publisher"
  pub_topic: "potbuddy/telemetry"
  username: ""
  password: ""

http:
  port: 8080

store:
  buffer_size: 100

database:
  dsn: "postgres://postgres:postgres@10.0.0.66:5432/potbuddy?sslmode=disable"

device_id: "esp32wroom-project"
